
name: "TaskMate"
description: "A simple task management application"
version: "1.0.0"
slug: "taskmate"
init: false
ingress: true
panel_icon: "mdi:check-box-outline"
panel_title: "TaskMate"
panel_admin: false
webui: "http://[HOST]:[PORT:8099]"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
